const fs = require('fs');

const enExtras = {
  "pcrTitle": "Patient Care Report",
  "fullName": "Full Name",
  "nicPassport": "NIC / Passport No.",
  "age": "Age",
  "bloodGroup": "Blood Group",
  "contactNo": "Contact No.",
  "guardianNextOfKin": "Guardian / Next of Kin",
  "relationship": "Relationship",
  "guardianContactNo": "Guardian Contact No.",
  "idFront": "ID Front",
  "idBack": "ID Back",
  "emergencyType": "Emergency Type",
  "chiefComplaint": "Chief Complaint / Description",
  "symptoms": "Symptoms",
  "consciousLevel": "Conscious Level",
  "painLevel010": "Pain Level (0 - 10)",
  "aAirway": "A - Airway",
  "airwayManaged": "Airway Managed?",
  "method": "Method",
  "bBreathing": "B - Breathing",
  "respRate": "Resp. Rate (/min)",
  "spo2": "SpO2 (%)",
  "breathingAssisted": "Breathing Assisted?",
  "cCirculation": "C - Circulation",
  "pulseMin": "Pulse (/min)",
  "bpMmHg": "BP (mmHg)",
  "capillaryRefill": "Capillary Refill",
  "bleedingControlled": "Bleeding Controlled?",
  "dDisability": "D - Disability",
  "gcsScore": "GCS Score:",
  "e14": "E (1-4)",
  "v15": "V (1-5)",
  "m16": "M (1-6)",
  "eExposure": "E - Exposure",
  "temperatureC": "Temperature (°C)",
  "noVitalsRecorded": "No vital signs recorded yet.",
  "timePulseBpSpo2": "Time: {time} | Pulse: {pulse} | BP: {bp} | SpO2: {spo2}",
  "@timePulseBpSpo2": {
    "placeholders": {
      "time": { "type": "String" },
      "pulse": { "type": "String" },
      "bp": { "type": "String" },
      "spo2": { "type": "String" }
    }
  },
  "logCurrentVitals": "Log Current Vitals",
  "sSignsSymptoms": "S - Signs & Symptoms",
  "aAllergies": "A - Allergies",
  "mMedications": "M - Medications",
  "pPastMedicalHistory": "P - Past Medical History",
  "lLastMeal": "L - Last Meal",
  "eEventsLeading": "E - Events Leading to Illness/Injury",
  "knownConditions": "Known Conditions",
  "interactiveBodyMapPlaceHolder": "Interactive Body Injury Map Placeholder",
  "interactiveBodyMapHint": "(Tap to add markers for burns, fractures, swelling, etc.)",
  "airwayManagement": "AIRWAY MANAGEMENT",
  "o2Flow": "O2 Flow (L/min)",
  "cardiovascular": "CARDIOVASCULAR",
  "immobilization": "IMMOBILIZATION",
  "medicationGiven": "MEDICATION GIVEN",
  "medication": "Medication",
  "dose": "Dose",
  "route": "Route",
  "time": "Time",
  "transportType": "Transport Type",
  "departureTime": "Departure Time",
  "arrivalTimeExt": "Arrival Time (Ext.)",
  "distanceCoveredKm": "Distance Covered (km)",
  "doctorNurseName": "Doctor / Nurse Name",
  "handoverTime": "Handover Time",
  "conditionOnArrival": "Condition on Arrival",
  "handoverNotes": "Handover Notes",
  "submitPcr": "SUBMIT PATIENT CARE REPORT",
  "reportSubmitted": "Report submitted successfully!",
  "errorSavingReport": "Error saving report: {error}",
  "@errorSavingReport": {
    "placeholders": {
      "error": { "type": "String" }
    }
  }
};

const siExtras = {
  "pcrTitle": "රෝගී සත්කාර වාර්තාව",
  "fullName": "සම්පූර්ණ නම",
  "nicPassport": "ජා.හැ.ප. / විදේශ ගමන් බලපත්‍රය",
  "age": "වයස",
  "bloodGroup": "රුධිර ගණය",
  "contactNo": "සම්බන්ධ කරගත යුතු අංකය",
  "guardianNextOfKin": "භාරකරු / ඥාතියා",
  "relationship": "ඥාතිත්වය",
  "guardianContactNo": "භාරකරුගේ දුරකථන අංකය",
  "idFront": "හැඳුනුම්පත ඉදිරිපස",
  "idBack": "හැඳුනුම්පත පසුපස",
  "emergencyType": "හදිසි තත්වයේ වර්ගය",
  "chiefComplaint": "ප්‍රධාන පැමිණිල්ල / විස්තරය",
  "symptoms": "රෝග ලක්ෂණ",
  "consciousLevel": "සිහිය ඇති මට්ටම",
  "painLevel010": "වේදනා මට්ටම (0 - 10)",
  "aAirway": "A - ශ්වසන මාර්ගය",
  "airwayManaged": "ශ්වසන මාර්ගය කළමනාකරණය කළාද?",
  "method": "ක්‍රමය",
  "bBreathing": "B - හුස්ම ගැනීම",
  "respRate": "ශ්වසන වේගය (/min)",
  "spo2": "SpO2 (%)",
  "breathingAssisted": "හුස්ම ගැනීමට සහාය වූවාද?",
  "cCirculation": "C - රුධිර සංසරණය",
  "pulseMin": "නාඩි (/min)",
  "bpMmHg": "රුධිර පීඩනය (mmHg)",
  "capillaryRefill": "Capillary Refill",
  "bleedingControlled": "රුධිර වහනය පාලනය කළාද?",
  "dDisability": "D - ආබාධිත බව",
  "gcsScore": "GCS අගය:",
  "e14": "E (1-4)",
  "v15": "V (1-5)",
  "m16": "M (1-6)",
  "eExposure": "E - නිරාවරණය",
  "temperatureC": "උෂ්ණත්වය (°C)",
  "noVitalsRecorded": "තාමත් ජීව සලකුණු වාර්තා කර නොමැත.",
  "timePulseBpSpo2": "වේලාව: {time} | නාඩි: {pulse} | රු.පී: {bp} | SpO2: {spo2}",
  "logCurrentVitals": "වත්මන් ජීව සලකුණු සටහන් කරන්න",
  "sSignsSymptoms": "S - සංඥා සහ ලක්ෂණ",
  "aAllergies": "A - අසාත්මිකතා",
  "mMedications": "M - ඖෂධ",
  "pPastMedicalHistory": "P - පෙර වෛද්‍ය ඉතිහාසය",
  "lLastMeal": "L - අවසන් ආහාරය",
  "eEventsLeading": "E - අසනීපයට/තුවාලයට හේතු වූ සිදුවීම්",
  "knownConditions": "දන්නා රෝගී තත්වයන්",
  "interactiveBodyMapPlaceHolder": "අන්තර්ක්‍රියාකාරී ශරීර තුවාල සිතියම",
  "interactiveBodyMapHint": "(පිලිස්සුම්, අස්ථි බිඳීම්, ඉදිමීම් ආදිය සඳහා සලකුණු එකතු කිරීමට තට්ටු කරන්න)",
  "airwayManagement": "ශ්වසන මාර්ග කළමනාකරණය",
  "o2Flow": "O2 ගලනය (L/min)",
  "cardiovascular": "හෘද වාහිනී",
  "immobilization": "නිශ්චල කිරීම",
  "medicationGiven": "ලබා දුන් ඖෂධ",
  "medication": "ඖෂධය",
  "dose": "මාත්‍රාව",
  "route": "මාර්ගය",
  "time": "වේලාව",
  "transportType": "ප්‍රවාහන වර්ගය",
  "departureTime": "පිටත් වූ වේලාව",
  "arrivalTimeExt": "පැමිණි වේලාව",
  "distanceCoveredKm": "ගමන් කළ දුර (km)",
  "doctorNurseName": "වෛද්‍ය / හෙද නම",
  "handoverTime": "භාර දුන් වේලාව",
  "conditionOnArrival": "පැමිණෙන විට තත්වය",
  "handoverNotes": "භාරදීමේ සටහන්",
  "submitPcr": "රෝගී සත්කාර වාර්තාව ඉදිරිපත් කරන්න",
  "reportSubmitted": "වාර්තාව සාර්ථකව ඉදිරිපත් කරන ලදි!",
  "errorSavingReport": "වාර්තාව සුරැකීමේ දෝෂයක්: {error}"
};

const taExtras = {
  "pcrTitle": "நோயாளி பராமரிப்பு அறிக்கை",
  "fullName": "முழு பெயர்",
  "nicPassport": "அடையாள அட்டை / கடவுச்சீட்டு எண்",
  "age": "வயது",
  "bloodGroup": "இரத்த வகை",
  "contactNo": "தொடர்பு எண்",
  "guardianNextOfKin": "பாதுகாவலர் / உறவினர்",
  "relationship": "உறவு",
  "guardianContactNo": "பாதுகாவலர் தொடர்பு எண்",
  "idFront": "அடையாள அட்டை முன்",
  "idBack": "அடையாள அட்டை பின்",
  "emergencyType": "அவசர வகை",
  "chiefComplaint": "முக்கிய புகார் / விவரம்",
  "symptoms": "அறிகுறிகள்",
  "consciousLevel": "உணர்வு நிலை",
  "painLevel010": "வலி நிலை (0 - 10)",
  "aAirway": "A - சுவாசப்பாதை",
  "airwayManaged": "சுவாசப்பாதை நிர்வகிக்கப்பட்டதா?",
  "method": "முறை",
  "bBreathing": "B - சுவாசம்",
  "respRate": "சுவாச வீதம் (/min)",
  "spo2": "SpO2 (%)",
  "breathingAssisted": "சுவாசம் உதவப்பட்டதா?",
  "cCirculation": "C - சுழற்சி",
  "pulseMin": "நாடித் துடிப்பு (/min)",
  "bpMmHg": "இரத்த அழுத்தம் (mmHg)",
  "capillaryRefill": "Capillary Refill",
  "bleedingControlled": "இரத்தப்போக்கு கட்டுப்படுத்தப்பட்டதா?",
  "dDisability": "D - இயலாமை",
  "gcsScore": "GCS மதிப்பெண்:",
  "e14": "E (1-4)",
  "v15": "V (1-5)",
  "m16": "M (1-6)",
  "eExposure": "E - வெளிப்பாடு",
  "temperatureC": "வெப்பநிலை (°C)",
  "noVitalsRecorded": "இதுவரை உயிர் அறிகுறிகள் பதிவு செய்யப்படவில்லை.",
  "timePulseBpSpo2": "நேரம்: {time} | நாடி: {pulse} | ர.அ: {bp} | SpO2: {spo2}",
  "logCurrentVitals": "தற்போதைய உயிர் அறிகுறிகளை பதிவு செய்",
  "sSignsSymptoms": "S - அறிகுறிகள் மற்றும் அடையாளங்கள்",
  "aAllergies": "A - ஒவ்வாமை",
  "mMedications": "M - மருந்துகள்",
  "pPastMedicalHistory": "P - கடந்தகால மருத்துவ வரலாறு",
  "lLastMeal": "L - கடைசி உணவு",
  "eEventsLeading": "E - நோய்/காயத்திற்கு வழிவகுத்த நிகழ்வுகள்",
  "knownConditions": "அறிந்த மருத்துவ நிலைகள்",
  "interactiveBodyMapPlaceHolder": "ஊடாடும் உடல் காயம் வரைபடம்",
  "interactiveBodyMapHint": "(தீக்காயங்கள், எலும்பு முறிவுகள், வீக்கம் போன்றவற்றைச் சேர்க்கத் தட்டவும்)",
  "airwayManagement": "சுவாசப்பாதை மேலாண்மை",
  "o2Flow": "O2 ஓட்டம் (L/min)",
  "cardiovascular": "இருதய அமைப்பு",
  "immobilization": "அசைவற்றாக்கம்",
  "medicationGiven": "அளிக்கப்பட்ட மருந்து",
  "medication": "மருந்து",
  "dose": "அளவு",
  "route": "பாதை",
  "time": "நேரம்",
  "transportType": "போக்குவரத்து வகை",
  "departureTime": "புறப்பட்ட நேரம்",
  "arrivalTimeExt": "வந்தடைந்த நேரம்",
  "distanceCoveredKm": "கடந்த தூரம் (கிமீ)",
  "doctorNurseName": "மருத்துவர் / செவிலியர் பெயர்",
  "handoverTime": "ஒப்படைக்கப்பட்ட நேரம்",
  "conditionOnArrival": "வந்தடையும் போது நிலை",
  "handoverNotes": "ஒப்படைப்பு குறிப்புகள்",
  "submitPcr": "நோயாளி பராமரிப்பு அறிக்கையைச் சமர்ப்பி",
  "reportSubmitted": "அறிக்கை வெற்றிகரமாக சமர்ப்பிக்கப்பட்டது!",
  "errorSavingReport": "அறிக்கையைச் சேமிப்பதில் பிழை: {error}"
};

function updateArb(file, extras) {
  let content = fs.readFileSync(file, 'utf8');
  let obj = JSON.parse(content);
  obj = { ...obj, ...extras };
  fs.writeFileSync(file, JSON.stringify(obj, null, 2));
}

updateArb('lib/l10n/app_en.arb', enExtras);
updateArb('lib/l10n/app_si.arb', siExtras);
updateArb('lib/l10n/app_ta.arb', taExtras);

console.log("PCR ARB files updated successfully");
