// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjnC2sjk6w9RtwfPaqc-FCoz4yHuoc1Zw',
    appId: '1:910920787307:android:8b60a0ab41d6fb0778182e',
    messagingSenderId: '910920787307',
    projectId: 'stj-medilink-plus',
    storageBucket: 'stj-medilink-plus.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwCD2V4X3pnBuQoAbWovfNReBLsY1gW34',
    appId: '1:910920787307:ios:07ad4de636fa008878182e',
    messagingSenderId: '910920787307',
    projectId: 'stj-medilink-plus',
    storageBucket: 'stj-medilink-plus.firebasestorage.app',
    iosClientId:
        '910920787307-kgub9hpr0rugkfoni8cmol0kh3k7nh88.apps.googleusercontent.com',
    iosBundleId: 'com.stj.stjMedilinkPlus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSrCTv1okm-YnWTbOXFixQuaoHMWU3Oww',
    appId: '1:910920787307:web:fa572091e7ae812078182e',
    messagingSenderId: '910920787307',
    projectId: 'stj-medilink-plus',
    storageBucket: 'stj-medilink-plus.firebasestorage.app',
    authDomain: 'stj-medilink-plus.firebaseapp.com',
    measurementId: 'G-2CNV6TD71E',
  );
}
